version: '3.8'

services:
  replicator:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - TARGET_GCS_BUCKET=${TARGET_GCS_BUCKET}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/gcp-credentials.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
